home/urls.py
from django.urls import path

from . import views
app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
]

mynti/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),

]

home/models.py
from django.db import models

# Create your models here.

phuyen/models.py
from django.db import models

# Create your models here.

class Places(models.Model):
    name: models.CharField(max_length=255, unique=True)
    picture: models.CharField()


class Food(models.Model):
    name: models.CharField(max_length=255, unique=True)
    picture: models.CharField()

home/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'home/index.html')

phuyen/views.py
from django.shortcuts import render

# Create your views here.

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>Material Design Bootstrap</title>
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <!-- Bootstrap core CSS -->
  <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet" >
  <!-- Material Design Bootstrap -->
  <link href="{% static "css/mdb.min.css" %}" rel="stylesheet" >
  <!-- Your custom styles (optional) -->
  <link href="{% static "css/styles.css" %}" rel="stylesheet" >
  <style type="text/css">




  </style>
</head>
<body>

<nav class="navbar fixed-top navbar-expand-lg navbar-dark scrolling-navbar">
    <div class="container">

      <!-- Brand -->
      <a class="navbar-brand" href="#" target="_blank">
        <strong>Mynti</strong>
      </a>

      <!-- Collapse -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Links -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <!-- Left -->
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url "home:index" %}">Home</a>
          </li>
        </ul>

        <!-- Right -->
        <ul class="navbar-nav nav-flex-icons">
          <li class="nav-item">
            <a href="https://www.facebook.com/joel.nguyenanh" class="nav-link" target="_blank">
                <i class="fa fa-facebook mr-2"></i>Facebook
            </a>
          </li>


        </ul>

      </div>

    </div>
  </nav>





{% block content %}

{% endblock %}

  <!-- SCRIPTS -->
  <!-- JQuery -->
  <script type="text/javascript" src="{% static "js/jquery-3.3.1.min.js" %}"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="{% static "js/popper.min.js"%}"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="{% static "js/bootstrap.min.js" %}"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="{% static "js/mdb.min.js" %}"></script>
  <!-- Initializations -->
  <script type="text/javascript">
    // Animations initialization
    new WOW().init();
  </script>

</body>
</html>

templates/home/index.html
{% extends 'base.html' %}
{% block content %}
    {% load staticfiles %}

  <!--Carousel Wrapper-->
  <div id="carousel-example-1z" class="carousel slide carousel-fade" data-ride="carousel">

    <!--Indicators-->
    <ol class="carousel-indicators">
      <li data-target="#carousel-example-1z" data-slide-to="0" class="active"></li>
      <li data-target="#carousel-example-1z" data-slide-to="1"></li>
    </ol>
    <!--/.Indicators-->

    <!--Slides-->
    <div class="carousel-inner" role="listbox">

      <!--First slide-->
      <div class="carousel-item active">
        <div class="view" style="background-image: url({% static "img/Phu-Yen.jpg" %}); background-repeat: no-repeat; background-size: cover;">

          <!-- Mask & flexbox options-->
          <div class="mask rgba-black-light d-flex justify-content-center align-items-center">

            <!-- Content -->
            <div class="text-center white-text mx-5 wow fadeIn">
              <h1 class="mb-4">
                <strong>Phú Yên</strong>
              </h1>

              <p>
                <strong>Ky My và Ngọc Anh</strong>
              </p>
            </div>
            <!-- Content -->

          </div>
          <!-- Mask & flexbox options-->

        </div>
      </div>
      <!--/First slide-->

      <!--Second slide-->
      <div class="carousel-item">
        <div class="view" style="background-image: url('https://scontent-syd2-1.xx.fbcdn.net/v/t31.0-8/28238419_1704670172928586_7016226483693274498_o.jpg?_nc_cat=102&oh=1b8310cf26f8e3183da68e3e26e3d79d&oe=5C48076C'); background-repeat: no-repeat; background-size: cover;">

          <!-- Mask & flexbox options-->
          <div class="mask rgba-black-light d-flex justify-content-center align-items-center">

            <!-- Content -->
            <div class="text-center white-text mx-5 wow fadeIn">
              <h1 class="mb-4">
                <strong>Phú Quốc</strong>
              </h1>

              <p>
                <strong>Ky My và Ngọc Anh</strong>
              </p>

            </div>
            <!-- Content -->

          </div>
          <!-- Mask & flexbox options-->

        </div>
      </div>
      <!--/Second slide-->



    </div>
    <!--/.Slides-->

    <!--Controls-->
    <a class="carousel-control-prev" href="#carousel-example-1z" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carousel-example-1z" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
    <!--/.Controls-->

  </div>
  <!--/.Carousel Wrapper-->





{% endblock %}